Repository heyloft/maraudersmap, pull requests merged in 2022-10, with the labels that each got.

#46 7 show pois on map
  .gitignore
  App.tsx
  README.md
  base.env
  env.d.ts
  package.json
  src/api/fetch-items.ts
  src/api/fetch-pois.ts
  src/api/utils/generic-fetch.ts
  src/client/core/ApiError.ts
  src/client/core/ApiRequestOptions.ts
  src/client/core/ApiResult.ts
  src/client/core/CancelablePromise.ts
  src/client/core/OpenAPI.ts
  src/client/core/request.ts
  src/client/index.ts
  src/client/models/HTTPValidationError.ts
  src/client/models/Item.ts
  src/client/models/ItemCreate.ts
  src/client/models/POI.ts
  src/client/models/POICreate.ts
  src/client/models/ValidationError.ts
  src/client/services/DefaultService.ts
  src/components/Map.tsx
  src/components/MarkerCard.tsx
  tsconfig.json
  yarn.lock
Labels: user story, tech story

#45 QR code scanner
  package.json
  src/components/QrScanner.tsx
  src/screens/ScannerScreen.tsx
  yarn.lock
Labels: enhancement

#49 22 to see the individual quest screen
  App.tsx
  package.json
  src/components/AbandonQuestDialog.tsx
  src/components/InduvidualQuest.tsx
  src/screens/QuestLogScreen.tsx
  src/screens/QuestNavigator.tsx
  src/screens/QuestScreen.tsx
Labels: user story

#61 54 basic login screen
  App.tsx
  src/recoil/atom.ts
  src/screens/AppNavigator.tsx
  src/screens/LogInScreen.tsx
  src/screens/MainScreen.tsx
  src/screens/ProfileScreen.tsx
  src/screens/QuestLogScreen.tsx
  src/screens/QuestNavigator.tsx
Labels: user story

#67 52 completed quest screen
  package.json
  src/components/QrScanner.tsx
  src/components/QuestCompletedModal.tsx
  yarn.lock
Labels: user story

#72 69 add userid to global state
  package.json
  src/api/get-user.ts
  src/api/utils/createUser.ts
  src/api/utils/generic-fetch.ts
  src/api/utils/generic-post.ts
  src/client/index.ts
  src/client/models/Event.ts
  src/client/models/EventCreate.ts
  src/client/models/EventParticipationCreate.ts
  src/client/models/Item.ts
  src/client/models/ItemBase.ts
  src/client/models/ItemCreate.ts
  src/client/models/ItemOwnership.ts
  src/client/models/ItemOwnershipCreate.ts
  src/client/models/ItemType.ts
  src/client/models/POI.ts
  src/client/models/Quest.ts
  src/client/models/QuestCreate.ts
  src/client/models/QuestDependencyBase.ts
  src/client/models/QuestDependencyCreate.ts
  src/client/models/QuestParticipation.ts
  src/client/models/QuestParticipationCreate.ts
  src/client/models/QuestParticipationUpdate.ts
  src/client/models/QuestStatus.ts
  src/client/models/UnlockMethod.ts
  src/client/models/User.ts
  src/client/models/UserBase.ts
  src/client/models/UserCreate.ts
  src/client/services/DefaultService.ts
  src/components/ErrorAlert.tsx
  src/recoil/atom.ts
  src/screens/AppNavigator.tsx
  src/screens/LogInScreen.tsx
  src/screens/ProfileScreen.tsx
  yarn.lock
Labels: user story

#75 74 see user owned items in bag
  src/api/get-item-ownerships.ts
  src/components/Map.tsx
  src/screens/BagScreen.tsx
Labels: user story, Frontend

#80 Unmount when not Bagscreen deselected
  src/screens/MainScreen.tsx
Labels: tech story, Frontend

#93 88 Welcome Modal
  src/components/WelcomeModal.tsx
  src/screens/MainScreen.tsx
Labels: enhancement, Frontend
